### ISSUE TITLE
Sometimes when training a thread error apears

### ISSUE THREAD

**Issue by coldmayo** [coldmayo/40kAI#34]
Error below:
Exception ignored in: <function Image.__del__ at 0x76e1523ede40>
Traceback (most recent call last):
  File "/usr/lib/python3.12/tkinter/__init__.py", line 4117, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x76e152d33560>
Traceback (most recent call last):
  File "/usr/lib/python3.12/tkinter/__init__.py", line 414, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x76e152d33560>
Traceback (most recent call last):
  File "/usr/lib/python3.12/tkinter/__init__.py", line 414, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x76e152d33560>
Traceback (most recent call last):
  File "/usr/lib/python3.12/tkinter/__init__.py", line 414, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x76e152d33560>
Traceback (most recent call last):
  File "/usr/lib/python3.12/tkinter/__init__.py", line 414, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: main thread is not in main loop
Tcl_AsyncDelete: async handler deleted by the wrong thread
./train.sh: line 3:  3646 Aborted                 (core dumped) python -u train.py

**Comment by coldmayo** [comment]
I have a few comments about this:
1. I am not using Tkinter so I am curious why this error is even happening
2. When restarting the training it works fine

**Comment by coldmayo** [comment]
Since this issue has not been reproduced I will close this issue.
